name: LaTeX Build

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    tags:
      - "v*"
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Check Out Code
        uses: actions/checkout@v3

      - name: Install Texlive Apt Dependencies
        uses: Eeems-Org/apt-cache-action@v1.1
        with:
          packages: texlive-full inkscape

      - name: Build LaTeX Document
        run: make all
        shell: bash

      - name: Check if Arbeit.pdf exists
        run: |
          if [ ! -f "Arbeit.pdf" ]; then
            echo "Arbeit.pdf was not found. For the diagnosis of possible errors, see previous output."
            exit 1
          fi

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Arbeit
          path: Arbeit.pdf

      - name: Set Tag
        id: set_tag
        if: startsWith(github.ref, 'refs/tags/v')
        run: echo "TAG=$(echo $GITHUB_REF | sed 's/refs\/tags\///')" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG }}
          release_name: Release ${{ env.TAG }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset
        if: steps.create_release.outputs.upload_url != ''
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: Arbeit.pdf
          asset_name: Arbeit_${{ env.TAG }}.pdf
          asset_content_type: application/pdf
